# ganti dengan menggunakna di 1 system operasi
services:
  mongodb-rant:
    image: mongo:7.0
    container_name: mongodb-rant
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dar
      MONGO_INITDB_ROOT_PASSWORD: dar-rant
    volumes:
      - ./data/mongo:/data/db
    networks:
      - rant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-express-rant:
    image: mongo-express:1.0.2-20-alpine3.19 # menggunakan versi alpine yang jauh lebih ringan
    container_name: mongo-express-rant
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Koneksi ke MongoDB
      ME_CONFIG_MONGODB_SERVER: mongodb-rant
      ME_CONFIG_MONGODB_PORT: 27017
      
      # Kredensial Admin untuk akses ke DB
      ME_CONFIG_MONGODB_ADMINUSERNAME: dar
      ME_CONFIG_MONGODB_ADMINPASSWORD: dar-rant
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      
      # Login untuk masuk ke Dashboard Mongo Express (Web UI)
      # Ganti sesuai keinginan agar tidak sembarang orang bisa buka port 8081
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: dar-rant
      
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongodb-rant:
        condition: service_healthy
    networks:
      - rant-network

networks:
  rant-network:
    driver: bridge
